#!/usr/bin/env python

"""
Tools Project
Copyright(c) 2017 Tools

This program is free software; you can redistribute it and/or modify it
under the terms and conditions of the GNU General Public License,
version 2, as published by the Free Software Foundation.

This program is distributed in the hope it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
more details.

You should have received a copy of the GNU General Public License along
with this program.  If not, see <http://www.gnu.org/licenses/>.

The full GNU General Public License is included in this distribution in
the file called "COPYING".

Contact Information:
Kamal Heib <kamalheib1@gmail.com>
"""

import re
import sys
from argparse import ArgumentParser

try:
    from git import Repo
except ImportError:
    print "Please Install GitPython Package (e.g. dnf install GitPython)"
    sys.exit(1)

SEARCH_PATHS = {
        'core': [
            'drivers/infiniband/Makefile',
            'drivers/infiniband/Kconfig',
            'drivers/infiniband/core/',
            'include/rdma/',
            'include/uapi/rdma/',
            'drivers/infiniband/sw/',
            ],
        'drivers': [
            'drivers/infiniband/hw/ehca/',
            'drivers/infiniband/hw/mthca/',
            'drivers/infiniband/hw/nes/',
            'drivers/infiniband/hw/ocrdma/',
            'drivers/net/ethernet/emulex/',
            'drivers/infiniband/hw/usnic/',
            'drivers/net/ethernet/cisco',
            'drivers/infiniband/hw/vmw_pvrdma',
            ],
        'ulps': [
            'drivers/infiniband/ulp/ipoib/',
            'drivers/infiniband/ulp/iser/',
            'drivers/infiniband/ulp/isert/',
            'drivers/infiniband/ulp/srp/',
            'drivers/scsi/scsi_transport_srp.c',
            'include/scsi/scsi_transport_srp.h',
            'drivers/infiniband/ulp/srpt/',
            'drivers/scsi/scsi_transport_srp.c',
            'include/scsi/scsi_transport_srp.h',
            'net/sunrpc/xprtrdma/',
            'include/linux/sunrpc/rpc_rdma.h',
            'include/linux/sunrpc/xprtrdma.h',
            ],
}

PICK_RGEX_LIST = [
    "cherry picked from commit ([0-9a-f]+)",
    "Cherry picked from commit ([0-9a-f]+)",
    "cherry picked from ([0-9a-f]+)",
    "Cherry picked from ([0-9a-f]+)",
    "upstream commit: ([0-9a-f]+)",
    "Upstream commit: ([0-9a-f]+)",
    "upstream commit ([0-9a-f]+)",
    "Upstream commit ([0-9a-f]+)",
    "upstream: ([0-9a-f]+)",
    "Upstream: ([0-9a-f]+)",
    "commit (([0-9a-f]+){10})",
    "Commit ([0-9a-f]+)"
]

IGNORE_COMMITS = [
        "1753a2f80cd3ebdda48c44469433499e60a2392a",
        "d718edd1ab0fa6508ab7e1a6b50d08cb845629af",
        "3bbccff60273510118eecbb8d316ab8dae327b78",
        "beb9ca4cf957e96f2916b0c4f7c98609b5726652",
        "380193320b040713de0a259cfbd72ae3e91f887e"
]

IGNORE_UPSTREAM_COMMITS = [
]


class git_change_log(object):
    def get_parser(self):
        if not hasattr(self, 'parser'):
            self.parser = ArgumentParser()
        return self.parser

    def parse_args(self, args):
        self.Parser.add_argument('-o', '--old_range', help='Old kernel range of commits', required=True)
        self.Parser.add_argument('-u', '--upstream_range', help='Upstream kernel range of commits', required=True)
        self.Parser.add_argument('--old_kernel_path', help='Path to old kernel tree', required=True)
        self.Parser.add_argument('--upstream_kernel_path', help='Path to upsream kernel tree', required=True)
        self.Parser.add_argument('--dirs', help='list of directorys to search for changes', nargs='+',
                                 choices=['core', 'drivers', 'ulps'], default=[ 'core', 'drivers', 'ulps'])
        self.Parser.add_argument('--debug', help="enable debug prints", action="store_true")

        self.Parser.parse_args(namespace=self, args=args)

    def get_old_repo(self):
        if not hasattr(self, 'old_repo'):
            self.old_repo = Repo(self.old_kernel_path)
        return self.old_repo

    def get_upstream_repo(self):
        if not hasattr(self, 'upstream_repo'):
            self.upstream_repo = Repo(self.upstream_kernel_path)
        return self.upstream_repo

    def get_included_commits(self):
        if not hasattr(self, 'included_commits_set'):
            self.included_commits_set = set()

            for commit in self.OldRepo.iter_commits(self.old_range, paths=self.RDMA_PATHS):
                match = None
                for regex in PICK_RGEX_LIST:
                    match = re.search(regex, commit.message)
                    if match:
                        break

                if match:
                    if self.debug:
                        print "Found:", commit
                        print regex
                    ignore = False
                    for msg in IGNORE_COMMITS:
                        if msg in commit.message:
                            ignore = True
                            break

                    if ignore:
                        continue

                    upstream_commit = self.UpstreamRepo.commit(match.group(1))
                    self.included_commits_set.add(upstream_commit.hexsha)
                else:
                    if self.debug:
                        print "Not found:", commit


        return self.included_commits_set

    def get_upstream_commits(self):
        if not hasattr(self, 'upstream_commits_set'):
            self.upstream_commits_set = set()

            for commit in self.UpstreamRepo.iter_commits(self.upstream_range, paths=self.RDMA_PATHS, no_merges=True):
                ignore = False
                for ignore_commit in IGNORE_UPSTREAM_COMMITS:
                    if ignore_commit in commit.summary:
                        ignore = True
                        break
                if ignore:
                    continue
                self.upstream_commits_set.add(commit.hexsha)

        return self.upstream_commits_set

    def get_not_included_commits(self):

        not_inclueded_commits = self.UpstreamCommits - self.IncludedCommits

        for commit in self.UpstreamRepo.iter_commits(self.upstream_range, paths=self.RDMA_PATHS, no_merges=True,
                                                     reverse=True):
            if commit.hexsha in not_inclueded_commits:
                msg = "%s # %s" % (commit, commit.summary)

                print msg

    def build_paths(self):
        self.RDMA_PATHS = []
        for directory in self.dirs:
            self.RDMA_PATHS += SEARCH_PATHS[directory]

    def execute(self, args):
        self.parse_args(args)
        self.build_paths()

        self.get_not_included_commits()

    Parser = property(get_parser)
    OldRepo = property(get_old_repo)
    UpstreamRepo = property(get_upstream_repo)
    IncludedCommits = property(get_included_commits)
    UpstreamCommits = property(get_upstream_commits)


if __name__ == '__main__':
    change_log = git_change_log()
    change_log.execute(sys.argv[1:])
