#!/usr/bin/env python

import os
import subprocess

result = subprocess.run('git branch --show-current', shell=True, capture_output=True, text=True)
branch = result.stdout.replace('-','_')
f = open('localversion', 'w')
f.write("." + branch)
f.close()
os.system("make -j 8 dist-brew")
